import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Script
          id="orchids-browser-logs"
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts/orchids-browser-logs.js"
          strategy="afterInteractive"
          data-orchids-project-id="227d548b-b8f5-4d86-a14b-344106766009"
        />
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
            <ThemeProvider>
                <Header />
                {children}
              </ThemeProvider>
          <VisualEditsMessenger />
            <script dangerouslySetInnerHTML={{ __html: `
              setTimeout(function() {
                var h = document.getElementById('site-header');
                var d = document.createElement('div');
                d.style.cssText = 'position:fixed;bottom:0;left:0;right:0;background:red;color:white;z-index:999999;font-size:11px;padding:8px;max-height:200px;overflow:auto';
                if (!h) { d.textContent = 'HEADER NOT FOUND'; document.body.appendChild(d); return; }
                var s = window.getComputedStyle(h);
                var info = 'HEADER: position=' + s.position + ' top=' + s.top + ' zIndex=' + s.zIndex + ' display=' + s.display;
                info += ' | scrollingEl=' + document.scrollingElement.tagName;
                info += ' | docEl.scrollH=' + document.documentElement.scrollHeight + ' body.scrollH=' + document.body.scrollHeight;
                info += ' | innerH=' + window.innerHeight;
                d.textContent = info;
                document.body.appendChild(d);
              }, 3000);
            `}} />
        </body>
    </html>
  );
}
